### ISSUE TITLE
Find solution to logging

### ISSUE THREAD

**Issue by Egor-Krivov** [neuro-ml/deep_pipe#18]
Find solution that is good enough for the logging:
- [x] It can be installed
- [x] It allows user to write logs
- [x] User can look at these logs with good interface
- [x] No memory leak

#15 #14

**Comment by maxme1** [comment]
tensorboard-easy is now available at PyPi.
Not sure how to test a file writer for memory leaks (:

**Comment by Egor-Krivov** [comment]
Open file writer, write message, close it, many-many times. Check that memory consumption doesn't increase with time

**Comment by maxme1** [comment]
done
