### ISSUE TITLE
Potential challenges for a backup system

### ISSUE THREAD

**Issue by maxme1** [neuro-ml/deep_pipe#50]
- The validator doesn't know which epoch it is. It will always start over from 0.
- Some objects (like policies) might be simply copied in the backup class, this means that reloading them from disk will change them only inside the backup class.

**Comment by maxme1** [comment]
https://docs.python.org/3/library/pickle.html#object.__getstate__
this must be the solution to the unpickling problem

**Comment by Egor-Krivov** [comment]
>     * The validator doesn't know which epoch it is. It will always start over from 0.
Any examples of such validators?

**Comment by maxme1** [comment]
For example @kondrat1997 has in synthesis a validator that also logs images. Now it simply increments the epoch inside itself after each log entry.

**Comment by Egor-Krivov** [comment]
Current interface is excessive, since policies should be provided both to checkpoint manager and train function

**Comment by Egor-Krivov** [comment]
Also, checkpoint manager need to receive inner parts of the model

**Comment by maxme1** [comment]
pytorch optimizers don't have `parameters` attribute, so the loader fails

**Comment by Egor-Krivov** [comment]
It works
