### ISSUE TITLE
map_ids_to_disk uses .npy extension

### ISSUE THREAD

**Issue by samokhinv** [neuro-ml/deep_pipe#53]
I can choose arbitrary save_func, but the extension remains the same.
https://github.com/neuro-ml/deep_pipe/blob/9a87ece82636cc2c020e0127dd1686d3a325ddb5/dpipe/commands.py#L96

For example, I may prefer to save predictions for the whole image in json, if my slice-wise predictions have different length.

**Comment by samokhinv** [comment]
As a consequence, when I want to load the file by dpipe.io.load, it mistakenly uses false loaders to read predictions

**Comment by maxme1** [comment]
Fixed, Now all appropriate functions from `commands` have an optional `ext` parameter.
