### ISSUE TITLE
Gradient scaler throws `AssertionError: No inf checks were recorded for this optimizer` in case of empty mask in `dpipe.torch.functional.masked_loss`

### ISSUE THREAD

**Issue by vovaf709** [neuro-ml/deep_pipe#75]
If all gradients of the model are `None`-s, then `scaler.step(optimizer)` fails with `AssertionError: No inf checks were recorded for this optimizer`.

If mask in `dpipe.torch.functional.masked_loss` is empty, it creates and returns 0 wrapped in a torch tensor. This tensor is "detached" from model graph, so during backward no gradients flow into model parameters gradients, they are all `None`-s and `scaler.step` fails.

This can be simply fixed by not returning new 0 tensor in `masked_loss`, but multiplying prediction by 0, so there will be not `None` but 0 gradients in model parameters.

**Comment by maxme1** [comment]
maybe just take the first element of the prediction and multiply by 0? otherwise, if the prediction is huge it might be an overhead

**Comment by maxme1** [comment]
no, just `prediction.flatten()[0]`. wouldn't this be enough?

**Comment by vovaf709** [comment]
I was worried that `prediction.flatten()[0]` somehow can be not affected by weights, so gradients will be `None`. But seems like it is an extremely exotic case
